import { Inter } from 'next/font/google'
import './globals.css'

import 'font-awesome/css/font-awesome.min.css';
import 'remixicon/fonts/remixicon.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Solar Assist Pro',
  description: 'Generated by Stegpearl',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
